### ISSUE TITLE
Weird behavior in Rust with OpenCV

### ISSUE THREAD

**Issue by Knovour** [kali/opencv-rust#12]
I wrote some code like this.

    extern crate opencv;

    use self::opencv::highgui;
    use self::opencv::core::Mat;

    fn main() {
        load("image/test.jpg");
    }

    fn load(path: &str) {
        let src: Mat = highgui::imread(path, 1).unwrap();

        if src.empty().unwrap() {
            println!("Img load error");
        }
        else {
            println!("Img load success");
        }
    }

When I run `cargo run` it shows `Img load error`.

However, when I added a `println!` at first line in `load` function like

    fn load(path: &str) {
        println!("whatever");
        let src: Mat = highgui::imread(path, 1).unwrap();

        if src.empty().unwrap() {
            println!("Img load error");
        }
        else {
            println!("Img load success");
        }
    }

It shows `Img load success`.

But when I change it to other code like `let a: i32 = 1;`, it shows `Img load error` again.

I have no idea what's going on.

System info:

 - OS: Manjaro Linux
 - Kernel: 4.3.0
 - Rust: 1.4.0

I had asked the same question [here](http://stackoverflow.com/questions/33941897/weird-behavior-in-rust-with-opencv).

**Comment by kali** [comment]
I'll have a look tomorrow, it's probably a problem in the crate indeed.

**Comment by kali** [comment]
ok. I can't reproduce it here :/ Could you tell me which one was the expected behaviour ? In other words, is test image there ?

**Comment by kali** [comment]
also, are you building in debug or release ?

**Comment by Knovour** [comment]
This is my folder structure.
![snapshot3](https://cloud.githubusercontent.com/assets/893846/11440587/ef957090-953e-11e5-96c4-d98903ac6444.png)

cargo.toml

```
[package]
name = "test"
version = "0.0.1"
authors = [ "Knovour <email>" ]

[dependencies]
opencv = "0.2.1"
```

**Comment by Knovour** [comment]
I just added `imshow` in the end of function and it all shows image window no matter `empty()` is true or false.

```
extern crate opencv;

use self::opencv::highgui;
use self::opencv::core::Mat;

fn main() {
  load("image/test.jpg");
}

fn load(path: &str) {
  let src: Mat = highgui::imread(path, 1).unwrap();

  if src.empty().unwrap() {
    println!("Img load error");
  }
  else {
    println!("Img load success");
  }

  highgui::named_window(path, highgui::CV_WINDOW_AUTOSIZE).unwrap();
  highgui::imshow(path, &src).unwrap();

  highgui::wait_key(0).unwrap();
}
```

![snapshot4](https://cloud.githubusercontent.com/assets/893846/11440662/5f92c4b0-953f-11e5-844e-4a43e4a884a7.png)


And I recreate the folder structure in Mac OSX, the `empty()` function always false but can show the image window, too.

**Comment by kali** [comment]
ok. let me try to sum this up:
1/ we're dealing with the "ok" case, we actually expect imread to find the image and load it.
2/ imshow works, showing the matrix is not empty and imread is actually working
3/ in some cases, empty() returns true instead of false.
4/ we have a 100% reproducibility on your linux system with the first version of the code
5/ neither you nor me managed to reproduced in on osx.

Are we good so far ?

**Comment by Knovour** [comment]
Yes.

**Comment by kali** [comment]
ok, i reproduce it too in with virtual machine running ubuntu. investigating.

**Comment by Knovour** [comment]
Thank you.

**Comment by kali** [comment]
ok, i think i nailed it. please try 0.2.2. nice catch :)

**Comment by Knovour** [comment]
YES! Both Linux and Mac OSX work perfectly!

Thank you.
