### ISSUE TITLE
try! in examples not failing on error

### ISSUE THREAD

**Issue by phdoerfler** [kali/opencv-rust#14]
I am still relatively new to rust and as such this might be a mistake on my end but I found that this:

    let mut cam = match highgui::VideoCapture::device(1) {
        Ok(cam) => {
            println!("Got it!");
            cam
        },
        Err(_) => {
            println!("Oh no! Trying another one…");
            try!(highgui::VideoCapture::device(0))
        }
    };

results in this:

```
$ target/debug/capture
Warning, camera failed to properly initialize!
Cleaned up camera.
Got it!
```

My understanding is, that `highgui::VideoCapture::device(1)` should fail (aka execute the `Err(_)` branch) if it can't properly initialize the camera. However it "succeeds" even though it can't access the camera 1 and thus runs the code in the `Ok(_)` branch rather than the one in the `Err(_)` branch.

The reason for my change is that on my system there is only one camera connected not two and all examples are hard coded to use the second camera.

The original code as in `video_capture.rs`:

    let mut cam = try!(highgui::VideoCapture::device(1));

**Comment by kali** [comment]
The rust wrapper uses the Result return types to deal with the possibility of a C++ exception. 

But failure to open the camera in the C++ is not materialized by an exception, instead you need to check isOpened() / is_opened()

See the C++ documentation here:
http://docs.opencv.org/master/d8/dfe/classcv_1_1VideoCapture.html#a57c0e81e83e60f36c83027dc2a188e80

**Comment by phdoerfler** [comment]
Thanks for clarifying this. I guess this behaviour makes sense seeing that the rust wrapper tries to closely recreate the C++ API.
