### ISSUE TITLE
Improvement wishlist

### ISSUE THREAD

**Issue by whitequark** [kali/opencv-rust#3]
Here are some things I would like to see as a user of opencv-rust:

  - [ ] Pull out the doxygen documentation into rustdoc. This would be the single largest usability improvement.
  - [ ] Put constants into a module called e.g. `consts` and then `pub use consts::*` in the parent module. This will keep rustdoc clean and easier to navigate.
  - [ ] Get rid of the `sys::` intermediate module. Since the main source of documentation is OpenCV itself, most of the things users will care about are inside the `sys::` hierarchy anyway, making it pointless. (I assume that the point of it was to mimic the `xxx-rust-sys` bindings; to separate the "raw" bindings from "high-level" API.)
  - [ ] Get rid of user-exposed, autogenerated `VectorOfwhatever`. Instead, add a single trait `Vector<T>` and implement it for whatever vector types are required.
  - [ ] Put nonspecific types like `Mat` and `Size` and `Vector` under `opencv`.
  - [ ] Do something that would mollify autocompletion engines such as [racer](https://github.com/phildawes/racer). (This might also be a Racer deficiency, not opencv-rust).
  - [ ] Don't return `Result` from functions that cannot raise (is it even in OpenCV docs?)

As a developer:
  - [ ] Don't use `include!` when building. It would be much more convenient to have an actual module hierarchy that makes sense. It shouldn't even be too hard to do, just group the file contents by the output module name / filename.
  - [ ] Unindent templated code using Python's `textwrap.dedent`.
  - [ ] Refactor the horror that `gen_rust.py` is, somehow, please...

**Comment by kali** [comment]
Thanks for the suggestions. I've heard them, I agree with some of them. I have implemented a few, at least to some extent. Some of them are unfortunately difficult and/or impractical (Result, VectorOf), and I don't know what's wrong with racer, I'm not using it.

Please open separate issues if anything need tracking.
