### ISSUE TITLE
VectorOf* is unsound

### ISSUE THREAD

**Issue by oli-obk** [kali/opencv-rust#8]
https://github.com/kali/opencv-rust/blob/master/gen_rust.py#L977-L986 implements for VectorOfMat a deref to `&[Mat]` for example. But the `Mat` type is just a struct with a pointer, so it's basically just a pointer to the C++ type. The values accessible through the slice are the C++-Type, not the Rust-Type. 

I'm working on this. Probably simply removing the deref and adding an `Index` impl

**Comment by oli-obk** [comment]
okay, my solution doesn't work... is there any way to differentiate between types that have a `ptr: *c_void` member and those that are directly represented like `DMatch`?

**Comment by kali** [comment]
i think something in the line of 

```
if isinstance(a.type, BoxedClassTypeInfo) or a.type.is_by_ptr
```

should do the trick

**Comment by kali** [comment]
DMatch and the like are SimpleClassTypeInfo or ValueStructTypeInfo
